### PR TITLE
Changed repo url, gpgkey and gpgcheck to attributes

### PR DESCRIPTION
**Pull request by tryan225**
Removed hardcoded urls for yum repo url and gpg key. I also changed the gpgcheck to an attribute.

### CODE REVIEW

**Comment by atheiman** [comment]
👍 squash your commits tho
```shell
git rebase -i HEAD~4
# read the instructions in the comments
# replace "pick" with "f" on the 2nd, 3rd, and 4th lines
# save and quit out of your editor
# push your updated commits (force will be required)
git push origin rundeck-repo-as-attribute -f
```

**Comment by tryan225** [comment]
Squashed.

**Comment by atheiman** [comment]
im assuming rundeck server isnt started up yet when rspec is running and call to api is returning 500.
options are:
- sleep at start of rspec
- update service definition / init script / ubuntu whatever to not signal service start success until url responds with a 200

**Comment by atheiman** [comment]
👍 @ARentz07 @pcross616 can we get a merge on this guy

**Comment by spion06** [comment]
+1

**Comment by bpcook61** [comment]
+1

**Comment by edwlarkey** [comment]
+1

**Comment by ARentz07** [comment]
👍 lgtm

**Pull request merged**
