### PR TITLE
Repo clean

### PR DESCRIPTION
**Pull request by damacus**
In response to #37 
Using https://rtyley.github.io/bfg-repo-cleaner/ 

--strip-blobs-bigger-than 1M  ~/cookbooks/rundeck.git

The repo size is now a slightly more reasonable 28mb

### CODE REVIEW

**Comment by pcross616** [comment]
ran bfg locally myself with your args and it didn't seem to push the changes to github.  Though locally it was smaller.  I then deleted the repo and re pulled.. still very large.  Need to investigate further.

**Comment by damacus** [comment]
I'll ping you some more of the options I ran, I had to do some extra things
to get it to push the repo changes.

**Comment by jmickle** [comment]
@pcross616 I think we can merge this one

**Comment by pcross616** [comment]
we cleaned it not via PR though.

**Pull request closed without merging**
