### PR TITLE
create rundeck api client library

### PR DESCRIPTION
**Pull request by atheiman**
- [x] api client library
- [x] rspec tests with net/http stubs
- [x] kitchen test responses from running Rundeck api

### CODE REVIEW

**Comment by pcross616** [comment]
This is look like a great new feature.  Let me know when its ready to review and test.

**Comment by atheiman** [comment]
hoping to finish it up tomorrow.. the idea is we can manage more resources within rundeck with the api than the CLI.

first thing i plan to use this for is updating projects according to data bag config. currently only new projects are created, existing projects are not updated. this leads to running project config drifting away from what is in source control.

**Comment by atheiman** [comment]
this is ready for review. only functionality thats missing is other wrapper methods on the api client (`#post`, `#put`, `#delete`), thats because i haven't messed around with with any api endpoints that support them yet.

when I use this for managing projects, i'll add at least a post and put method

**Comment by bpcook61** [comment]
This is a great start to a lot of improvement opportunities.  Thanks Austin.
👍

**Comment by edwlarkey** [comment]
👍

**Comment by ARentz07** [comment]
:1st_place_medal: 👍

**Comment by atheiman** [comment]
@pcross616 let me know if you want me to make any updates

**Pull request merged**
