### PR TITLE
kitchen test in travis - fixes #110

### LINKED ISSUE #110: travis kitchen tests
https://github.com/zuazo/kitchen-in-travis

### PR DESCRIPTION
**Pull request by atheiman**
these suites will be run in travis:
- linting (rubocop, foodcritic)
- chefspec
- test-kitchen (centos)
- test-kitchen (ubuntu)

### CODE REVIEW

**Comment by atheiman** [comment]
this is at the point where its running linting, chefspec, kitchen centos, and kitchen ubuntu in separate builds. just need to ensure kitchen tests are actually succeeding 🙏

**Comment by atheiman** [comment]
ok, kitchen tests failed for both, but im gonna propose we merge this anyway. we can follow up with fix for the package install failures that are shown in the travis logs. I think that fix is in progress already anyway.

either way, this should be a big help to actually ensure tests are passing before merge

**Comment by atheiman** [comment]
@ARentz07 @spion06 @pcross616 @bpcook61 @snehitgajjar

**Comment by bpcook61** [comment]
Your centos suite won't pass until Issue 106 is fixed.

**Comment by atheiman** [comment]
@pcross616 can you review the travis test-kitchen output? maybe you know what the fix to this is?

https://travis-ci.org/Webtrends/rundeck/jobs/182364020
https://travis-ci.org/Webtrends/rundeck/jobs/182364023

**Comment by atheiman** [comment]
Ok I was having difficulty testing this locally today due to https://github.com/test-kitchen/kitchen-vagrant/issues/245

got that resolved and with this current code Im able to run a kitchen test locally with vagrant. based on a quick read of this issue https://github.com/docker/docker/issues/2296 Im thinking the some parts of this chef-client wont be able to be tested in docker in Travis. Im going to play with this a little to determine which parts of the kitchen run list are failing in travis docker container.

**Comment by atheiman** [comment]
kitchen tests passing for centos 6.8 and ubuntu 14.04 locally now with vagrant.

**Comment by atheiman** [comment]
ok, at this point I dont think Im going to be able to get kitchen tests running with Docker due to a few contributing factors:

- logic for various service providers in recipes needs improvement
- my understanding of docker and kitchen-docker is very limited
- there are challenges with running systemd, upstart, and sysvinit in docker containers

Once kitchen tests are working with docker, this travis config should get them running on pull requests tho.

Im going to open another PR for improved chefspec tests and working kitchen tests for ubuntu and centos with the logic Brian added in a pr. When I have more time or a better understanding of docker I'll look at this again, or if anyone else has time feel free to poke around with kitchen-docker on this cookbook.

**Comment by atheiman** [comment]
closing, #120 resolved this

**Pull request closed without merging**
