### PR TITLE
Made some rundeck framework properties configurable.

### PR DESCRIPTION
**Pull request by nilroy**
This will allow us to set the rundeck server URL and the rundeck URL with the FQDN of the rundeck server. Otherwise once we login to the web console it will redirect to http://localhost:4440 which will obviously not work.

### CODE REVIEW

**Comment by pcross616** [comment]
are you using RD via apache?  It should proxy that for your correctly.  Unless RD changed something, recently.

**Comment by nilroy** [comment]
Well I am using RD without apache...With apache its throwing error like I don't have permission to access ...I shall check again(maybe because I changed the localhost to the hostname of the server in frameworks.properties configuration it is throwing error).

**Comment by nilroy** [comment]
I changed the framework.properties file to point to localhost.. But something apache is blocking...I could not fix that problem. I am seeing below error

================
Forbidden

You don't have permission to access / on this server.
=================

**Comment by nilroy** [comment]
How about changing localhost in rundeck apache config to the FQDN of the rundeck server. In that case the system sill work both with and without apache reverse proxy. What do you say?
In my case somehow the apache configuration is not working. So I can work without the reverse proxy

**Comment by nilroy** [comment]
@pcross616 Any thought on this?

**Comment by pcross616** [comment]
testing this.. :)

**Comment by nilroy** [comment]
cool :)

**Pull request merged**
