### PR TITLE
Merge 3.x changes to master

### PR DESCRIPTION
**Pull request by ARentz07**
Requesting to get the 3.x changes into the master branch. 

❗ Please review the changelog as well, as this is a previously unreviewed update meant to include all the changes from 3.x.

Follow up to #90

### CODE REVIEW

**Comment by ARentz07** [comment]
Will address the foodcritic offenses.

**Comment by pcross616** [comment]
thx for the rebase.

**Comment by ARentz07** [comment]
Pushed up some changes that address all the rubocop/foodcritic issues. 

I disabled the `Lint/AssignmentInCondition` rule, since I didn't particularly see any value in updating the code, as it is more readable as-is than it would be if we updated it to be compliant with this rule.

**Comment by pcross616** [comment]
Can you please check, the build in master?  this seemed to have an issue during merge.

**Comment by ARentz07** [comment]
From the diff, it looks like nothing changed during the merge: https://github.com/Webtrends/rundeck/compare/master...ARentz07:3.x-rebased?expand=1

I'm seeing this though: 
```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:250:in `find_spec_for_exe': can't find gem chef-dk (>= 0.a) (Gem::GemNotFoundException)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
	from /opt/chefdk/embedded/bin/chef:22:in `<main>'
```

**Comment by ARentz07** [comment]
Tried kicking the build off again to see if it was something transitive, but I am seeing the same error again. 

Digging a bit deeper I see this also 
```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'chef' (= 12.14.12) among 19 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/travis/.rvm/gems/ruby-1.9.3-p551:/home/travis/.rvm/gems/ruby-1.9.3-p551@global', execute `gem env` for more information
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:320:in `to_spec'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /opt/chefdk/bin/chef:4:in `<main>'
```

In the previous [build](https://travis-ci.org/Webtrends/rundeck/builds/154543135) from the pull request, we were using chef-12.13.37, [which does seem to be the latest at the moment](https://rubygems.org/gems/chef/versions/12.13.37). 

It looks like there have been more releases of chef since then; in fact, [12.14.12](https://github.com/chef/chef/releases/tag/v12.14.12) is somewhat old now. However, these releases aren't showing up on Rubygems. 

Is there a way we can lock the version of chef down to something known to exist?

**Comment by ARentz07** [comment]
Hmm, looks like chef's own [ominbus_updater](https://github.com/chef-cookbooks/omnibus_updater) is also having the same issue. 

https://travis-ci.org/chef-cookbooks/omnibus_updater/builds/155042758

Maybe we should reach out?

**Comment by ARentz07** [comment]
I logged an issue to chef-dk regarding this. 

https://github.com/chef/chef-dk/issues/997

**Comment by ARentz07** [comment]
Build successful 👍 
https://travis-ci.org/Webtrends/rundeck/builds/154596524

**Pull request merged**
